[project]
author = "Aditya"
description = "A* pathfinding algorithm implementation written in python for the pathfinding into programming project"
version = "v1.0"
license = "MIT"

[settings]
cell_size = 20
row_cells = 40
col_cells = 40  
add_wait_time = true
